service: picture-battle-websocket-server

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  connectHandler:
    handler: handler.connect
    events:
      - websocket:
          route: $connect

  disconnectHandler:
    handler: handler.disconnect
    events:
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: handler.default
    events:
      - websocket:
          route: $default
