service: picture-battle-websocket-server

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  connectHandler:
    handler: src/handlers/index.connect
    events:
      - websocket:
          route: $connect

  disconnectHandler:
    handler: src/handlers/index.disconnect
    events:
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: src/handlers/index.defaultHandler
    events:
      - websocket:
          route: $default

  echoHandler:
    handler: src/handlers/index.echoHandler
    events:
      - websocket:
          route: echo
