service: picture-battle-websocket-server

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    GAME_TABLE_NAME: picture-battle-games
    CONNECTION_TABLE_NAME: picture-battle-connections
    PLAYER_TABLE_NAME: picture-battle-players

plugins:
  - serverless-offline

functions:
  connectHandler:
    handler: src/handlers/index.connect
    events:
      - websocket:
          route: $connect

  disconnectHandler:
    handler: src/handlers/index.disconnect
    events:
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: src/handlers/index.defaultHandler
    events:
      - websocket:
          route: $default

  echoHandler:
    handler: src/handlers/index.echoHandler
    events:
      - websocket:
          route: echo

  initHandler:
    handler: src/handlers/index.initHandler
    events:
      - websocket:
          route: init

  createGameHandler:
    handler: src/handlers/index.createGameHandler
    events:
      - websocket:
          route: createGame
