service: picture-battle-websocket-server

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    GAME_TABLE_NAME: picture-battle-games
    CONNECTION_TABLE_NAME: picture-battle-connections
    PLAYER_TABLE_NAME: picture-battle-players
    ACTION_TABLE_NAME: picture-battle-actions

plugins:
  - serverless-offline

functions:
  connectHandler:
    handler: src/handlers/index.connect
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    timeout: 29
    events:
      - websocket:
          route: $connect

  disconnectHandler:
    handler: src/handlers/index.disconnect
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    timeout: 29
    events:
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: src/handlers/index.defaultHandler
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    timeout: 29
    events:
      - websocket:
          route: $default

  initHandler:
    handler: src/handlers/index.initHandler
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    timeout: 29
    events:
      - websocket:
          route: init

  createGameHandler:
    handler: src/handlers/index.createGameHandler
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    timeout: 29
    events:
      - websocket:
          route: createGame

  joinGameHandler:
    handler: src/handlers/index.joinGameHandler
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    timeout: 29
    events:
      - websocket:
          route: joinGame

  selectCharacterHandler:
    handler: src/handlers/index.selectCharacterHandler
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    timeout: 29
    events:
      - websocket:
          route: selectCharacter

  doActionHandler:
    handler: src/handlers/index.doActionHandler
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    timeout: 29
    events:
      - websocket:
          route: doAction
